// Package dialect 统一 SQLite/PostgreSQL 数据源接入：DSN 规范化、连接池
// 策略与占位符方言重写，供 agentstore/relaystore/upstreamstore/account 四个
// store 包共用（design/deployment-modes.md 2.2）。Kiro 外部凭据库
// （creds_file/cli_db）是只读导入源，不经本包，维持 SQLite。
package dialect

import (
	"database/sql"
	"fmt"
	"net/url"
	"path/filepath"
	"strconv"
	"strings"

	_ "github.com/jackc/pgx/v5/stdlib" // 注册 postgres 驱动名 "pgx"
	_ "modernc.org/sqlite"             // 注册 sqlite 驱动名 "sqlite"
)

const (
	SQLite   = "sqlite"
	Postgres = "postgres"
)

// Valid 报告 driver 是否受支持。
func Valid(driver string) bool { return driver == SQLite || driver == Postgres }

// SQLiteDSN 把裸文件路径补齐本系统统一的 pragma DSN。
// 不用 WAL：其 shm/mmap 在 Docker Desktop Windows 绑定挂载上会静默丢写；
// journal_mode 持久化在库文件里，显式 DELETE 确保旧 WAL 库也被切回回滚日志模式。
func SQLiteDSN(path string) string {
	return "file:" + path + "?_pragma=busy_timeout(5000)&_pragma=journal_mode(DELETE)&_pragma=foreign_keys(ON)"
}

// Open 打开连接池并应用方言池策略：sqlite 恒单连接（单写者语义，写并发弱，
// 串行化最稳）；postgres 走 pgx stdlib，池上限 10（部署可经 DSN 参数调整）。
// sqlite 的 dsn 为裸文件路径时自动补 pragma；以 file: 开头视为现成 DSN 原样使用。
func Open(driver, dsn string) (*sql.DB, error) {
	switch driver {
	case SQLite:
		if !strings.HasPrefix(dsn, "file:") {
			dsn = SQLiteDSN(dsn)
		}
		db, err := sql.Open("sqlite", dsn)
		if err != nil {
			return nil, fmt.Errorf("dialect: open sqlite: %w", err)
		}
		db.SetMaxOpenConns(1)
		return db, nil
	case Postgres:
		db, err := sql.Open("pgx", dsn)
		if err != nil {
			return nil, fmt.Errorf("dialect: open postgres: %w", err)
		}
		db.SetMaxOpenConns(10)
		db.SetMaxIdleConns(10)
		return db, nil
	default:
		return nil, fmt.Errorf("dialect: unsupported driver %q", driver)
	}
}

// Rebind 将 ? 占位符按序重写为 postgres 的 $n；sqlite 原样返回。
// 本仓 SQL 不含字面 '?' 字符串，简单扫描即可。
func Rebind(driver, query string) string {
	if driver != Postgres {
		return query
	}
	var b strings.Builder
	b.Grow(len(query) + 8)
	n := 0
	for i := 0; i < len(query); i++ {
		if query[i] == '?' {
			n++
			b.WriteByte('$')
			b.WriteString(strconv.Itoa(n))
		} else {
			b.WriteByte(query[i])
		}
	}
	return b.String()
}

// IdentityPK 返回各方言的自增主键子句（agentstore outbox 与 account
// usage_log 的 id 列）：sqlite 用 AUTOINCREMENT 防止 rowid 复用，
// postgres 用 IDENTITY。
func IdentityPK(driver string) string {
	if driver == Postgres {
		return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
	}
	return "INTEGER PRIMARY KEY AUTOINCREMENT"
}

// OpenSQLiteReadOnly 只读打开 SQLite 库（mode=ro + query_only，单连接），
// 作为迁移/导入的源库：绝对路径经 Windows 盘符转 URI 规范化。
func OpenSQLiteReadOnly(abs string) (*sql.DB, error) {
	uriPath := filepath.ToSlash(abs)
	if len(uriPath) >= 2 && uriPath[1] == ':' {
		uriPath = "/" + uriPath
	}
	u := &url.URL{Scheme: "file", Path: uriPath, RawQuery: "mode=ro&_pragma=query_only(1)"}
	db, err := sql.Open("sqlite", u.String())
	if err != nil {
		return nil, fmt.Errorf("dialect: open sqlite read-only: %w", err)
	}
	db.SetMaxOpenConns(1)
	return db, nil
}

// SQLitePath 从 sqlite DSN 提取库文件路径（裸路径或 file: URI 均可）；
// postgres 返回空串。
func SQLitePath(driver, dsn string) string {
	if driver != SQLite {
		return ""
	}
	path := strings.TrimPrefix(dsn, "file:")
	if i := strings.IndexByte(path, '?'); i >= 0 {
		path = path[:i]
	}
	return path
}

// WithDatabase 重写 postgres DSN 的库名（跨方言测试/工具按模块分库用）。
func WithDatabase(dsn, name string) (string, error) {
	u, err := url.Parse(dsn)
	if err != nil {
		return "", fmt.Errorf("dialect: parse dsn: %w", err)
	}
	u.Path = "/" + strings.TrimPrefix(name, "/")
	return u.String(), nil
}

// DatabaseName 取 postgres DSN 的库名（去前导 /）。
func DatabaseName(dsn string) string {
	u, err := url.Parse(dsn)
	if err != nil {
		return ""
	}
	return strings.TrimPrefix(u.Path, "/")
}
