package dialect

import (
	"path/filepath"
	"testing"
)

func TestRebindSQLitePassthrough(t *testing.T) {
	q := `INSERT INTO t(a,b) VALUES(?,?)`
	if got := Rebind(SQLite, q); got != q {
		t.Fatalf("sqlite rebind changed query: %s", got)
	}
}

func TestRebindPostgres(t *testing.T) {
	cases := []struct{ in, want string }{
		{`SELECT * FROM t WHERE a=? AND b=?`, `SELECT * FROM t WHERE a=$1 AND b=$2`},
		{`UPDATE t SET x=? WHERE id=?`, `UPDATE t SET x=$1 WHERE id=$2`},
		{`SELECT 1`, `SELECT 1`},
	}
	for _, c := range cases {
		if got := Rebind(Postgres, c.in); got != c.want {
			t.Fatalf("Rebind(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestSQLiteDSN(t *testing.T) {
	got := SQLiteDSN(`C:/data/agent.db`)
	want := "file:C:/data/agent.db?_pragma=busy_timeout(5000)&_pragma=journal_mode(DELETE)&_pragma=foreign_keys(ON)"
	if got != want {
		t.Fatalf("SQLiteDSN = %q, want %q", got, want)
	}
}

func TestIdentityPK(t *testing.T) {
	if got := IdentityPK(SQLite); got != "INTEGER PRIMARY KEY AUTOINCREMENT" {
		t.Fatalf("sqlite identity = %q", got)
	}
	if got := IdentityPK(Postgres); got != "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" {
		t.Fatalf("postgres identity = %q", got)
	}
}

func TestOpenUnsupportedDriver(t *testing.T) {
	if _, err := Open("mysql", "dsn"); err == nil {
		t.Fatal("expected error for unsupported driver")
	}
}

// Open sqlite 裸路径自动补 pragma，且可建表读写（驱动注册与 DSN 组装冒烟）。
func TestOpenSQLiteRoundtrip(t *testing.T) {
	db, err := Open(SQLite, filepath.Join(t.TempDir(), "t.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if _, err := db.Exec(`CREATE TABLE t(id INTEGER PRIMARY KEY, v TEXT NOT NULL)`); err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(`INSERT INTO t(v) VALUES(?)`, "x"); err != nil {
		t.Fatal(err)
	}
	var v string
	if err := db.QueryRow(`SELECT v FROM t WHERE id=?`, 1).Scan(&v); err != nil {
		t.Fatal(err)
	}
	if v != "x" {
		t.Fatalf("v = %q", v)
	}
}

// Open sqlite 已带 file: 前缀的 DSN 原样使用（不二次包装）。
func TestOpenSQLiteDSNPassthrough(t *testing.T) {
	path := filepath.Join(t.TempDir(), "t.db")
	dsn := SQLiteDSN(path)
	db, err := Open(SQLite, dsn)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if _, err := db.Exec(`SELECT 1`); err != nil {
		t.Fatal(err)
	}
}
